### ISSUE TITLE
OpenShift 3.11 router error in nginx.conf in image

### ISSUE THREAD

**Issue by magicalyak** [nginxinc/nginx-plus-router#13]
**Describe the bug**
Router won't start on OSE 3.11 due to error in nginx.conf in image

**To reproduce**
1. Follow deployment steps
2. inspect logs of router pod
3. 

**Expected behavior**

**Your environment**
* NGINX Router version v3.11.0+948efc6-96
* Openshift version 
oc v3.11.59
kubernetes v1.11.0+d4cacc0
* NGINX or NGINX Plus version

**Additional context**
Add any other context about the problem here. Any log files you want to share.
```
I0208 20:39:24.593652       1 template.go:297] Starting template router (v3.11.0+948efc6-96)
I0208 20:39:24.639036       1 router.go:481] Router reloaded:
Router was successfully started.
I0208 20:39:24.639139       1 router.go:252] Router is including routes in all namespaces
E0208 20:39:26.465930       1 limiter.go:137] error reloading router: exit status 1
nginx: [emerg] invalid parameter "weight=0" in /var/lib/nginx/conf/nginx.conf:1749
Failed to reload NGINX.
```

**Comment by magicalyak** [comment]
So one of the projects has a blue/green deployment and I see the weight set to 0, not sure why that fails though? Is that not allowed?  It pulled it from the existing router

        # endpoints of coolstore-prod-demo/inventory-blue
    server 10.128.2.165:8080 weight=256;


        # endpoints of coolstore-prod-demo/inventory-green
    server 10.129.3.101:8080 weight=0;

**Comment by magicalyak** [comment]
Below is the weighting through openshift that works with haproxy but not nginx. Stopping the pod with 0 works but starting causing the reload of nginx to fail say "invalid parameter" as above

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: '2019-02-01T20:05:56Z'
  labels:
    app: inventory
    demo: coolstore-microservice
    template: inventory-bluegreen
    variant: green
  name: inventory
  namespace: coolstore-prod-demo
  resourceVersion: '31661295'
  selfLink: /apis/route.openshift.io/v1/namespaces/coolstore-prod-demo/routes/inventory
  uid: c922a88a-265c-11e9-8364-001a4a0ba48f
spec:
  alternateBackends:
    - kind: Service
      name: inventory-green
      weight: 0
  host: inventory-coolstore-prod-demo.paas.rdu.salab.redhat.com
  to:
    kind: Service
    name: inventory-blue
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-02-01T20:05:56Z'
          status: 'True'
          type: Admitted
      host: inventory-coolstore-prod-demo.paas.rdu.salab.redhat.com
      routerName: router
      wildcardPolicy: None

```

This is taken from a Red Hat OpenShift demo project
https://github.com/jbossdemocentral/coolstore-microservice

**Comment by pleshakov** [comment]
@magicalyak 
thanks for reporting and the details! this is a bug. we'll fix it shortly.
