### ISSUE TITLE
External routes are not working

### ISSUE THREAD

**Issue by TFK1410** [nginxinc/nginx-plus-router#17]
I've followed the guide: nginx-oss-router-install.md to deploy the nginx router on a fresh OpenShift 3.11 cluster. The image was downloaded and added to my registry. The deployment itself is there and it is working:
```
$ oc get dc router
NAME      REVISION   DESIRED   CURRENT   TRIGGERED BY
router    1          1         1         config
$ oc get service router
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                   AGE
router    ClusterIP   172.30.93.111   <none>        80/TCP,443/TCP,1936/TCP   1d
```
However now when I can't access any external route. I get the connection refused error. 
The router logs don't show any errors besides the one line below in repetition:
```
W0409 09:09:29.260137 1 reflector.go:272] github.com/openshift/origin/pkg/router/controller/factory/factory.go:112: watch of *v1.Route ended with: The resourceVersion for the provided watch is too old.
W0409 09:17:44.312835 1 reflector.go:272] github.com/openshift/origin/pkg/router/controller/factory/factory.go:112: watch of *v1.Route ended with: The resourceVersion for the provided watch is too old.
```

**Comment by pleshakov** [comment]
@TFK1410 
how do you access the Router?

**Comment by TFK1410** [comment]
What do you mean exactly?
I'm still able to access the OpenShift cluster and the router deployment through the web console and CLI. Is there some other logs that I can get you?

**Comment by pleshakov** [comment]
@TFK1410 My bad. Below are some clarifying questions.

> However now when I can't access any external route.

What client do you use to access external routes? 
How is the Router pod exposed to the client? Do the client connect to the Router through one of the cluster nodes? Does the client connect to the Router through a load balancer for the Router service?

**Comment by tux-o-matic** [comment]
Helping @TFK1410  on this: the Router is running on an infra node, no load balancer in front but actually the DeploymentConfig didn't ensure replica on each infra nodes so that was the first thing to solve. Then needed to ensure *reload-nginx* was executable by all.
