### ISSUE TITLE
HTTP_X_FORWARDED_PORT incorrect on Passthrough routes

### ISSUE THREAD

**Issue by amon-ra** [nginxinc/nginx-plus-router#19]
**Describe the bug**
The variable HTTP_X_FORWARDED_PORT=10444 pased to backend contaniners when we use passthrough routes when it must be 80 or 443.

**To reproduce**
1. Create route.
2. Show variables in backend

**Expected behavior**
 HTTP_X_FORWARDED_PORT=80 or  HTTP_X_FORWARDED_PORT=443

**Your environment**
* NGINX Router 0.2
* Openshift 3.11
* NGINX 1.1.5.6

**Additional context**

**Comment by pleshakov** [comment]
thanks for reporting. the bug is confirmed. a solution is proposed in https://github.com/nginxinc/nginx-openshift-router/pull/18#issuecomment-482635179
