### ISSUE TITLE
Support snippets annotations

### ISSUE THREAD

**Issue by pleshakov** [nginxinc/nginx-plus-router#20]
**Is your feature request related to a problem? Please describe.**

Allows the user to customize NGINX configuration in ways that are not possible via the existing annotations/ env variables. This will enable support for advanced use cases/customization.

**Describe the solution you'd like**
Use cases:
* As a Router admin, I would like to allow the Router users to customize NGINX configuration for their Routes.
* As a Router user, I would like to customize NGINX configuration for my Routes.

Configuration:
* `ROUTER_ENABLE_UNSAFE_ANNOTATIONS` . Enables support for unsafe annotations in Routes -- annotations that are not validated by the Router and might lead to invalid NGINX configuration. The default is `false`.
* `unsafe.nginx.router.openshift.io/server-snippets`.  Sets custom snippets in the server context of the generated NGINX config.  If multiple routes are created for the same host and all have this annotation present, the annotation of the primary route will be used. The primary route is a route which name is the alphabetically last among all routes. If some routes have TLS termination enabled, the primary route is a route which name is the alphabetically last among all TLS-enabled routes. Note: The Router doesn't validate this annotation, which might lead to invalid NGINX configuration. Check the Router logs to makes sure that the annotation has been successfully applied.
* `unsafe.nginx.router.openshift.io/location-snippets`. Sets custom snippets in the location context of the generated NGINX config. Note: The Router doesn't validate this annotation, which might lead to invalid NGINX configuration. Check the Router logs to makes sure that the annotation has been successfully applied.

Note: because the snippets annotations might lead to invalid NGINX configuration, it makes sense to mark them as "unsafe" and mandate that the Router admin must explicitly enable them in the Router."

Behavior: 
Assuming that the ROUTER_ENABLE_UNSAFE_ANNOTATIONS env is set to true for the Router.
* if `unsafe.nginx.router.openshift.io/server-snippets` is present in a Route, its value is inserted in the server context of the generated NGINX config. This applies for HTTP, Passthrough and TCP/UDP Routes. If multiple Routes are created for the same host, only the annotations from the primary Route is used.
* If `unsafe.nginx.router.openshift.io/location-snippets` is present in a Route, its value is inserted in the location context. This is not applied for Passthrough or TCP/UDP Routes. This should work for both regular and gRPC locations.

**Describe alternatives you've considered**

- Modifying the template and inserting the necessary NGINX configuration.
- Creating custom annotations -- modifying the template and adding new annotations for a particular use case.

**Additional context**

* Based on the proposal in https://github.com/nginxinc/nginx-openshift-router/pull/18
* The feature is similar to the snippets annotations in the NGINX Ingress Controller -- https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/configmap-and-annotations.md#snippets-and-custom-templates
* Also, the custom annotations feature in the NGINX Ingress Controller -- https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/custom-annotations.md

**Comment by Rikbruggink** [comment]
@pleshakov This looks reasonable to implement. Admins can enable disable the feature. I will try to work on a pull request later this week implenting this or is it something you are already working at?

**Comment by pleshakov** [comment]
@Rikbruggink 
we'd be happy to review a PR! we haven't started implementing this feature.

**Comment by Rikbruggink** [comment]
With #22 merged, i think this one can be closed. @pleshakov
